### ISSUE TITLE
PreCache option is deleting the file after TS Completes

### ISSUE THREAD

**Issue by TANielsen** [MSEndpointMgr/ModernDriverManagement#5]
How do I specify where to download the drivers so it does not delete them all when the TS completes?  I want to precache the drivers locally so the next task sequence (user initiated) runs it and they're already downloaded to a specific location.  IE C:\Drivers

**Comment by NickolajA** [comment]
Hi, are you using the new version 4.x of the script, or an older? Our intention is to store the content in the CCMCache, which should not be cleaned out after a TS completes (although it's been some time since I last looked through the end segment of a smsts.log file). Perhaps we could add a parameter that provides you with an override to specify a custom path, like C:\Path, using -PreCacheDirectory 'C:\Path'. What do you think?

**Comment by TANielsen** [comment]
Hi Nickolaj,  I figured out that the "precache" option does store in the CCMcache folder.  However, when the task sequence actually runs in "upgrade" mode, it then copies the data from CCMCache to the c:\_SMSTS folder.  That is OK.  I sort of agree that it would be nice to be able to specify a location to store the cached drivers so it doesn't get confusing later on.
